import { useState, useEffect, useCallback, useMemo } from "react";
import {
  eachDayOfInterval,
  endOfDay,
  endOfMonth,
  format,
  parse,
  parseISO,
  startOfDay,
  startOfMonth,
} from "date-fns";
import { toast } from "react-toastify";
import { useSelector } from "react-redux";
import { newAttendanceService } from "@/appwrite/newAttendanceService";
import holidayService from "@/appwrite/holidaysService";
import batchService from "@/appwrite/batchService";
import tradeservice from "@/appwrite/tradedetails";
import { selectActiveBatchId } from "@/store/activeBatchSlice";

const STATUS_ALIASES = {
  p: "present",
  present: "present",
  a: "absent",
  absent: "absent",
  l: "leave",
  leave: "leave",
  onleave: "leave",
  on_leave: "leave",
};

const normalizeStatus = (rawStatus) => {
  const value = String(rawStatus || "").trim().toLowerCase();
  return STATUS_ALIASES[value] || value;
};

const normalizeDate = (value) => {
  if (!value) return null;
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value;
  try {
    const dateObj =
      typeof value === "string" && value.includes("T")
        ? parseISO(value)
        : new Date(value);
    if (Number.isNaN(dateObj.getTime())) return null;
    return format(dateObj, "yyyy-MM-dd");
  } catch {
    return null;
  }
};

const isSecondOrFourthSaturday = (dateObj) => {
  if (dateObj.getDay() !== 6) return false;
  const weekNumber = Math.ceil(dateObj.getDate() / 7);
  return weekNumber === 2 || weekNumber === 4;
};

const normalizeAttendanceData = (records = []) => {
  const byDate = new Map();
  const invalid = [];

  records.forEach((record) => {
    const date = normalizeDate(record?.date);
    const status = normalizeStatus(record?.status);
    if (!date || !["present", "absent", "leave"].includes(status)) {
      invalid.push(record);
      return;
    }

    const normalized = {
      ...record,
      date,
      status,
      markedAt: record?.markedAt || null,
    };

    const current = byDate.get(date);
    if (!current) {
      byDate.set(date, normalized);
      return;
    }

    const currentTs = new Date(
      current?.$updatedAt || current?.markedAt || current?.$createdAt || 0
    ).getTime();
    const candidateTs = new Date(
      normalized?.$updatedAt || normalized?.markedAt || normalized?.$createdAt || 0
    ).getTime();
    if (candidateTs >= currentTs) byDate.set(date, normalized);
  });

  return { byDate, records: Array.from(byDate.values()), invalid };
};

const generateWorkingDays = ({ startDate, endDate, holidaysMap }) => {
  if (!startDate || !endDate || startDate > endDate) return [];
  return eachDayOfInterval({ start: startDate, end: endDate })
    .map((dateObj) => ({ dateObj, date: format(dateObj, "yyyy-MM-dd") }))
    .filter(({ dateObj, date }) => {
      if (holidaysMap.has(date)) return false;
      if (dateObj.getDay() === 0) return false;
      if (isSecondOrFourthSaturday(dateObj)) return false;
      return true;
    })
    .map(({ date }) => date);
};

const buildAttendanceMap = ({ workingDaysList, attendanceByDate, profile, batchId }) => {
  const finalMap = new Map();
  workingDaysList.forEach((date) => {
    const existing = attendanceByDate.get(date);
    if (existing) {
      finalMap.set(date, { ...existing, autoGenerated: false });
      return;
    }
    finalMap.set(date, {
      userId: profile?.userId || null,
      batchId: batchId || null,
      tradeId: profile?.tradeId || null,
      date,
      status: "absent",
      markedAt: null,
      remarks: "Auto-marked absent (no record)",
      autoGenerated: true,
    });
  });
  return finalMap;
};

const calculateStats = (attendanceMap, holidayDays = 0) => {
  let presentDays = 0;
  let absentDays = 0;
  let leaveDays = 0;

  attendanceMap.forEach((record) => {
    if (record.status === "present") presentDays += 1;
    else if (record.status === "leave") leaveDays += 1;
    else absentDays += 1;
  });

  const totalDays = attendanceMap.size;
  return {
    totalDays,
    presentDays,
    absentDays,
    leaveDays,
    holidayDays,
    attendancePercentage:
      totalDays > 0 ? Number(((presentDays / totalDays) * 100).toFixed(2)) : 0,
  };
};

const toMinutes = (time, fallback) => {
  const [h, m] = String(time || fallback).split(":").map((v) => Number(v || 0));
  return h * 60 + m;
};

export const useStudentAttendance = (profile) => {
  const activeBatchId = useSelector(selectActiveBatchId);
  const resolvedBatchId = activeBatchId;
  const isResolvingBatch = !activeBatchId && !!profile?.userId;

  const [isLoadingAttendance, setIsLoadingAttendance] = useState(false);
  const [batchData, setBatchData] = useState(null);
  const [rawMonthlyRecords, setRawMonthlyRecords] = useState([]);
  const [holidays, setHolidays] = useState(new Map());
  const [invalidRecords, setInvalidRecords] = useState([]);
  const [refreshStatsCounter, setRefreshStatsCounter] = useState(0);
  const [currentMonth, setCurrentMonth] = useState(format(new Date(), "MMMM yyyy"));
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [lastUpdatedDate, setLastUpdatedDate] = useState(null);
  const [overallStats, setOverallStats] = useState(null);
  const [tradeData, setTradeData] = useState(null);

  const fetchBatchData = useCallback(async (batchId) => {
    try {
      const data = await batchService.getBatch(batchId);
      setBatchData(data || null);
    } catch (error) {
      console.log(error);
    }
  }, []);

  const fetchTradeData = useCallback(async (tradeId) => {
    try {
      const data = await tradeservice.getTrade(tradeId);
      setTradeData(data || null);
    } catch (error) {
      console.log(error);
    }
  }, []);


  useEffect(() => {
    if (resolvedBatchId) fetchBatchData(resolvedBatchId);
  }, [resolvedBatchId, fetchBatchData]);

  useEffect(() => {
    if (batchData?.tradeId) fetchTradeData(batchData.tradeId);
  }, [batchData?.tradeId, fetchTradeData]);

  const getMonthRange = useCallback((monthLabel) => {
    const parsedDate = parse(monthLabel, "MMMM yyyy", new Date());
    return { start: startOfMonth(parsedDate), end: endOfMonth(parsedDate) };
  }, []);

  const fetchMonthlyAttendance = useCallback(async () => {
    if (!resolvedBatchId || !profile?.userId) return;
    setIsLoadingAttendance(true);
    try {
      const { start, end } = getMonthRange(currentMonth);
      const batchStart = batchData?.start_date
        ? startOfDay(new Date(batchData.start_date))
        : start;
      const batchEnd = batchData?.end_date
        ? endOfDay(new Date(batchData.end_date))
        : endOfDay(end);
      const todayEnd = endOfDay(new Date());

      const rangeStart = new Date(Math.max(start.getTime(), batchStart.getTime()));
      const rangeEnd = new Date(Math.min(endOfDay(end).getTime(), batchEnd.getTime(), todayEnd.getTime()));

      const startDate = format(rangeStart, "yyyy-MM-dd");
      const endDate = format(rangeEnd, "yyyy-MM-dd");

      const [attendanceRes, holidayRes] = await Promise.all([
        newAttendanceService.getStudentAttendanceByDateRange(
          profile.userId,
          resolvedBatchId,
          startDate,
          endDate
        ),
        holidayService.getBatchHolidaysByDateRange(
          resolvedBatchId,
          startDate,
          endDate
        ),
      ]);

      setRawMonthlyRecords(attendanceRes?.documents || []);
      const holidayMap = new Map();
      (holidayRes || []).forEach((item) => {
        const date = normalizeDate(item?.date);
        if (!date) return;
        if (date > endDate || date < startDate) return;
        holidayMap.set(date, String(item?.holidayText || "Holiday").trim());
      });
      setHolidays(holidayMap);
    } catch (error) {
      console.log(error);
      toast.error("Failed to fetch attendance.");
    } finally {
      setIsLoadingAttendance(false);
    }
  }, [profile, currentMonth, getMonthRange, batchData, resolvedBatchId]);

  useEffect(() => {
    fetchMonthlyAttendance();
  }, [fetchMonthlyAttendance, refreshStatsCounter]);

  const fetchOverallStats = useCallback(async () => {
    if (!profile?.userId || !resolvedBatchId) return;
    try {
      const stats = await newAttendanceService.getStudentAttendanceStats(
        profile.userId,
        resolvedBatchId
      );
      setOverallStats({
        totalDays: stats.total,
        presentDays: stats.presentDays,
        absentDays: stats.absentDays,
        attendancePercentage: stats.percentage,
        leaveDays: 0,
      });
    } catch (error) {
      console.error("Error fetching overall stats:", error);
    }
  }, [profile, resolvedBatchId]);

  useEffect(() => {
    fetchOverallStats();
  }, [fetchOverallStats, refreshStatsCounter]);

  const normalized = useMemo(
    () => normalizeAttendanceData(rawMonthlyRecords),
    [rawMonthlyRecords]
  );

  useEffect(() => {
    setInvalidRecords(normalized.invalid);
  }, [normalized.invalid]);

  const workingDaysList = useMemo(() => {
    if (!batchData?.start_date) return [];
    const { start: monthStart, end: monthEnd } = getMonthRange(currentMonth);
    const batchStart = startOfDay(new Date(batchData.start_date));
    const batchEnd = batchData?.end_date
      ? endOfDay(new Date(batchData.end_date))
      : endOfDay(new Date());
    const today = endOfDay(new Date());

    const rangeStart = new Date(Math.max(monthStart.getTime(), batchStart.getTime()));
    const rangeEnd = new Date(Math.min(monthEnd.getTime(), batchEnd.getTime(), today.getTime()));

    return generateWorkingDays({
      startDate: rangeStart,
      endDate: rangeEnd,
      holidaysMap: holidays,
    });
  }, [batchData, currentMonth, getMonthRange, holidays]);

  const finalAttendanceMap = useMemo(
    () =>
      buildAttendanceMap({
        workingDaysList,
        attendanceByDate: normalized.byDate,
        profile,
        batchId: resolvedBatchId,
      }),
    [workingDaysList, normalized.byDate, profile, resolvedBatchId]
  );

  const finalAttendanceRecords = useMemo(
    () =>
      Array.from(finalAttendanceMap.values()).sort(
        (a, b) => new Date(b.date) - new Date(a.date)
      ),
    [finalAttendanceMap]
  );

  const stats = useMemo(() => calculateStats(finalAttendanceMap, holidays.size), [finalAttendanceMap, holidays.size]);

  const studentAttendance = useMemo(
    () => ({
      ...profile,
      attendanceRecords: finalAttendanceRecords,
      batchId: resolvedBatchId,
    }),
    [profile, finalAttendanceRecords, resolvedBatchId]
  );

  const markAttendance = async (dateStr, status = "present", remarks = "") => {
    try {
      if (!batchData?.canMarkAttendance) {
        toast.warn("Attendance marking is disabled for this batch.");
        return null;
      }
      const normalizedDate = normalizeDate(dateStr);
      if (!normalizedDate) {
        toast.error("Invalid date.");
        return null;
      }

      const today = format(new Date(), "yyyy-MM-dd");
      if (normalizedDate > today) {
        toast.warn("Future dates cannot be marked.");
        return null;
      }
      if (normalizedDate < today && !batchData?.canMarkPrevious) {
        toast.warn("Past attendance marking is disabled.");
        return null;
      }
      if (holidays.has(normalizedDate)) {
        toast.warn("Cannot mark attendance on a holiday.");
        return null;
      }
      if (
        batchData?.start_date &&
        normalizedDate < normalizeDate(batchData.start_date)
      ) {
        toast.warn("Date is before batch start.");
        return null;
      }
      if (batchData?.end_date && normalizedDate > normalizeDate(batchData.end_date)) {
        toast.warn("Date is after batch end.");
        return null;
      }

      const nowMins = new Date().getHours() * 60 + new Date().getMinutes();
      const startMins = toMinutes(batchData?.attendanceTime?.start, "09:00");
      const endMins = toMinutes(batchData?.attendanceTime?.end, "18:00");
      if (normalizedDate === today && (nowMins < startMins || nowMins > endMins)) {
        toast.warn("Attendance can only be marked within attendance time.");
        return null;
      }

      const existing = normalized.byDate.get(normalizedDate);
      const safeStatus = normalizeStatus(status);
      let result;
      if (existing) {
        result = await newAttendanceService.updateAttendance(existing.$id, {
          status: safeStatus,
          remarks,
          markedBy: profile?.userId,
        });
      } else {
        result = await newAttendanceService.createAttendance({
          userId: profile?.userId,
          batchId: resolvedBatchId,
          tradeId: profile?.tradeId || null,
          date: normalizedDate,
          status: safeStatus,
          remarks,
          markedBy: profile?.userId,
        });
      }

      // Update only the changed date locally to avoid full-month refetch flicker.
      setRawMonthlyRecords((prev) => {
        const next = Array.isArray(prev) ? [...prev] : [];
        const idx = next.findIndex((r) => normalizeDate(r?.date) === normalizedDate);
        const merged = {
          ...(idx >= 0 ? next[idx] : {}),
          ...(result || {}),
          date: normalizedDate,
          status: safeStatus,
          remarks,
          markedBy: profile?.userId,
          markedAt: result?.markedAt || new Date().toISOString(),
        };
        if (idx >= 0) next[idx] = merged;
        else next.push(merged);
        return next;
      });
      setLastUpdatedDate(normalizedDate);
      setTimeout(() => setLastUpdatedDate(null), 2200);

      toast.success("Attendance saved successfully!");
      return result;
    } catch (error) {
      console.error("Error marking attendance:", error);
      toast.error("Failed to mark attendance.");
      throw error;
    }
  };

  useEffect(() => {
    console.groupCollapsed("[StudentAttendance][Debug] Core data snapshot");
    console.log("Student profile:", profile || {});
    console.log("Batch data:", batchData || {});
    console.log("Holidays:", Array.from(holidays.entries()));
    console.log("Raw monthly records:", rawMonthlyRecords);
    console.log("Normalized records:", normalized.records);
    console.log("Working days:", workingDaysList);
    console.log("Final attendance map:", finalAttendanceMap);
    console.log("Invalid records:", invalidRecords);
    console.groupEnd();
  }, [
    profile,
    batchData,
    holidays,
    rawMonthlyRecords,
    normalized.records,
    workingDaysList,
    finalAttendanceMap,
    invalidRecords,
  ]);

  return {
    isLoadingAttendance: isLoadingAttendance || isResolvingBatch,
    batchData,
    tradeData,
    studentAttendance,
    holidays,
    workingDays: finalAttendanceMap,
    finalAttendanceMap,
    finalAttendanceRecords,
    workingDaysList,
    attendanceByDate: finalAttendanceMap,
    attendanceStats: stats,
    monthlyStats: stats,
    overallStats,
    currentMonth,
    selectedDate,
    setSelectedDate,
    handleMonthChange: (dateOrStr) => {
      const month =
        typeof dateOrStr === "string" ? dateOrStr : format(dateOrStr, "MMMM yyyy");
      setCurrentMonth(month);
      if (typeof dateOrStr !== "string") setSelectedDate(dateOrStr);
    },
    markAttendance,
    lastUpdatedDate,
    refreshStats: () => setRefreshStatsCounter((prev) => prev + 1),
    invalidRecords,
  };
};
