const conf = {
  appwriteUrl: import.meta.env.VITE_APPWRITE_URL || import.meta.env.VITE_APPWRITE_ENDPOINT || "",
  projectId: import.meta.env.VITE_APPWRITE_PROJECT_ID || "",
  databaseId: import.meta.env.VITE_APPWRITE_DATABASE_ID || "",
  quesCollectionId: import.meta.env.VITE_APPWRITE_QUES_COLLECTION_ID || "",
  questionPapersCollectionId: import.meta.env.VITE_QUESTIONPAPER_COLLECTION_ID || "",
  tradeCollectionId: import.meta.env.VITE_TRADE_COLLECTION_ID || "",
  bucketId: import.meta.env.VITE_APPWRITE_BUCKET_ID || "",
  userStatsCollectionId: import.meta.env.VITE_USER_STATS_COLLECTION_ID || "",
  userProfilesCollectionId: import.meta.env.VITE_USER_PROFILE_COLLECTION_ID || "",
  batchesCollectionId: import.meta.env.VITE_BATCH_COLLECTION_ID || "",
  collegeTradeCollectionId: import.meta.env.VITE_COLLEGE_TRADE_COLLECTION_ID || "",
  collegesCollectionId: import.meta.env.VITE_COLLEGE_COLLECTION_ID || "",
  subjectsCollectionId: import.meta.env.VITE_SUBJECTS_COLLECTION_ID || "",
  modulesesCollectionId: import.meta.env.VITE_MODULES_COLLECTION_ID || "",
  mockTestFunctionId: import.meta.env.VITE_MOCKTEST_FUNCTION_ID || "",
  studentAttendanceCollectionId: import.meta.env.VITE_ATTAINDANCE_COLLECTION_ID || "",
  faceAttendanceCollectionId: "6800d3c9000712f842e3",
  newAttendanceCollectionId: import.meta.env.VITE_NEW_ATTENDANCE_COLLECTION_ID || "",
  holidayDaysCollectionId: import.meta.env.VITE_HOLIDAY_DAYS_COLLECTION_ID || "",
  batchRequestsCollectionId: import.meta.env.VITE_BATCH_REQUESTS_COLLECTION_ID || "batchRequests",
  batchStudentsCollectionId: import.meta.env.VITE_BATCH_STUDENTS_COLLECTION_ID || "batchStudents",
  profileImagesBucketId: "mocktestimages",
};

export default conf;
