import { Group, Search, Building2, Briefcase } from "lucide-react";
import {
  FaBook,
  FaBookReader,
  FaCalendarAlt,
  FaCalendarCheck,
  FaDashcube,
  FaFileAlt,
  FaHome,
  FaInfoCircle,
  FaKey,
  FaLayerGroup,
  FaList,
  FaQuestionCircle,
  FaRegCalendarCheck,
  FaUserPlus,
  FaUserSecret,
  FaBell,
} from "react-icons/fa";
import { 
  MdAddCard, 
  MdGroupAdd, 
} from "react-icons/md";

export const menuConfig = [
  {
    group: "Overview",
    icon: FaHome,
    children: [
      { label: "Home", path: "/", icon: FaHome },
      { label: "Game Arena", path: "/arena", icon: FaDashcube, requiresAuth: true },
      { label: "About", path: "/about", icon: FaInfoCircle },
    ],
  },
  {
    group: "Learning & Tests",
    icon: FaBook,
    children: [
      {
        label: "My Assessments",
        path: "/assessment",
        icon: MdAddCard,
        requiresAuth: true,
        requiresBatch: true,
      },
      {
        label: "Create Question",
        path: "/create-question",
        icon: FaQuestionCircle,
        roles: ["teacher"],
        requiresAuth: true,
      },
      {
        label: "Manage Questions",
        path: "/manage-questions",
        icon: FaList,
        roles: ["teacher"],
        requiresAuth: true,
      },
      {
        label: "Create Mock Exam",
        path: "/mock-exam",
        icon: FaBook,
        roles: ["teacher", "student"],
        requiresAuth: true,
      },
      {
        label: "Take Mock Exam",
        path: "/attain-test",
        icon: FaKey,
        requiresAuth: true,
      },
      {
        label: "My Mock Exams",
        path: "/all-mock-tests",
        icon: FaFileAlt,
        requiresAuth: true,
      },
    ],
  },
  {
    group: "Batches",
    icon: FaLayerGroup,
    children: [
      {
        label: "Batch Setup",
        path: "/batches/create",
        activePaths: [
          "/batches/create", "/batches/settings", "/batches/:batchId/settings",
          "/manage-batch/create", "/manage-batch/edit", "/manage-batch/edit/:batchId",
        ],
        icon: MdGroupAdd,
        roles: ["teacher"],
        requiresAuth: true,
      },
      {
        label: "Manage Enrollment",
        path: "/batches/students",
        activePaths: ["/batches/students", "/batches/:batchId/students", "/manage-batch/students"],
        icon: FaUserPlus,
        roles: ["teacher"],
        requiresAuth: true,
      },
      {
        label: "Batch Records & Activity",
        path: "/batches/records",
        activePaths: ["/batches/records", "/batches/:batchId/records", "/manage-batch/view"],
        icon: FaList,
        roles: ["teacher"],
        requiresAuth: true,
      },
      {
        label: "Browse Batches",
        path: "/browse-batches",
        icon: Search,
        roles: ["student"],
        requiresAuth: true,
      },
    ],
  },
  {
    group: "Attendance",
    icon: FaCalendarCheck,
    children: [
      {
        label: "Mark My Attendance",
        path: "/attendance/mark-my-attendance",
        icon: FaRegCalendarCheck,
        roles: ["teacher", "student"],
        requiresAuth: true,
        requiresBatch: true,
      },
      {
        label: "Attendance Register",
        path: "/attendance/register",
        icon: FaCalendarAlt,
        roles: ["teacher"],
        requiresAuth: true,
        requiresBatch: true,
      },
      {
        label: "My Attendance",
        path: "/student-attendance",
        icon: FaCalendarCheck,
        roles: ["student"],
        requiresAuth: true,
        requiresBatch: true,
      },
      { label: "Daily Diary", path: "/daily-diary", icon: FaBookReader, requiresAuth: true, requiresBatch: true },
      {
        label: "College Attendance",
        path: "/attendance/college-attendance",
        icon: FaCalendarCheck,
        roles: ["admin", "teacher"],
        requiresAuth: true,
        requiresBatch: true,
      },
    ],
  },
  {
    group: "Administration",
    icon: FaUserSecret,
    roles: ["admin"],
    requiresAuth: true,
    children: [
      { label: "Modules", path: "/add-modules", icon: MdAddCard, requiresAuth: true },
      { label: "Questions", path: "/add-bulk-questions", icon: Group, requiresAuth: true },
      { label: "Colleges", path: "/manage-colleges", icon: Building2, requiresAuth: true },
      { label: "Trades", path: "/manage-trades", icon: Briefcase, requiresAuth: true },
      { label: "Notification Tester", path: "/test-notifications", icon: FaBell, requiresAuth: true },
    ],
  },
];

export const pathToHeading = {
  "/": "Home",
  "/arena": "Game Arena",
  "/profile": "Profile",
  "/batches": "Batch Setup",
  "/batches/create": "Create Batch",
  "/batches/settings": "Batch Settings",
  "/batches/students": "Manage Enrollment",
  "/batches/records": "Batch Records & Activity",
  "/manage-batch": "Batch Setup",
  "/manage-batch/create": "Create Batch",
  "/manage-batch/edit": "Batch Settings",
  "/manage-batch/students": "Manage Enrollment",
  "/manage-batch/view": "Batch Records & Activity",
  "/create-question": "Create Question",
  "/manage-questions": "Manage Questions",
  "/manage-colleges": "Manage Colleges",
  "/manage-trades": "Manage Trades",
  "/test-notifications": "Notification Diagnostics & Push Tester",
  "/mock-exam": "Create Mock Exam",
  "/attain-test": "Take Mock Exam",
  "/all-mock-tests": "My Mock Exams",
  "/assessment": "My Assessments",
  "/daily-diary": "Daily Diary",
  "/student-attendance": "My Attendance",
  "/attendance/register": "Attendance Register",
  "/attendance/mark-my-attendance": "Mark My Attendance",
  "/attendance/marktoday": "Mark My Attendance",
  "/attendance/college-attendance": "College Attendance",
  "/browse-batches": "Browse Batches",
  "/about": "About",
  "/login": "Login",
  "/signup": "SignUp",
};
